Repository vimistify/AmbuFlow, pull requests merged in 2024-10, with the labels that each got.

#80 Revert "Diva711 patch 1"
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: Level 3, gssoc-ext, hacktoberfest

#68 Fix: Centered the logo
  hospital.html
Labels: gssoc-ext, level 2, hacktoberfest

#164 Added a footer section
  contact.html
  features.html
  home.html
  team.html
Labels: hacktoberfest, hacktoberfest-accepted, GSSOC'24 extd

#239 Enhance Logo Animation and Styling
  index.html
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#266 Update login.html fix#262
  login.html
Labels: level3, gssoc-extd, hacktoberfest, hacktoberfest-accepted

#284 [FIX] Footer updated
  index.html
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#295 corrected copyright and footer background of team page
  team.html
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#312 Improved manage.html
  home.html
  images/manageLogo.png
  index.html
  manage.html
  src/css/index.css
  src/css/manage.css
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#358 Optimised it for mobile or any screen size
  homepage.html
  index.html
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#537 Update README.md
  README.md
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#538 Add Hover Effects to Team and Contact Features
  homepage.html
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#594 [FIX] Feature Page - Double Grid Solved
  features.html
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#579 Fixed navigation link for contact us
  script.js
  style1.css
  team.html
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#530 Fix cursor trail effect bug on home page
  contact.html
  index.html
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#616 [FIX] Contact Page Nav Bar Added
  contact.html
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#605 Improved CSS styling and fixed layout issues in index.html
  index.html
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#618 [FIX] FAQ Section Added
  index.html
  src/css/up.css
  style1.css
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#651 changed code of conduct to version 2.1
  .github/workflows/static.yml
  CODE_OF_CONDUCT.md
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#684 added robots.txt
  robots.txt
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#673 [FIX] Double contact us icons removed
  contact.html
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#709 updated privacy.html break layout
  privacy.html
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#713 Enabling Dark Mode Toggle Button and adding it on every relative page… #701
  Feedback.html
  contact.html
  features.html
  index.html
  team.html
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#558 footer added at about us and also margin settled for about us section from top and bottom
  about.html
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#699 faq smooth transition and animations
  index.html
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#698 added language translator
  Feedback.html
  contact.html
  features.html
  index.html
  team.html
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#623 [Fix] : Home Page UI FIX #604
  index.html
  src/css/index.css
  style1.css
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#622 [FIX] Fixed Issue #578
  index.html
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#717 ADDED THE TRANSLATOR
  Feedback.html
  contact.html
  features.html
  index.html
  login.html
  nearby.html
  team.html
  up.html
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#769 apply hover effect and box shadow
  index.html
  style.css
  style1.css
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#753 boxes at nov bar components not looking good so i remove then and ap…
  index.html
  src/css/index.css
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#703 Home page UI change
  images/ambulance-gif.gif
  index.html
  src/css/index.css
  src/css/indexmain.css
  team.html
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#829 Removed unnecessary files used by Failing cron job
  .github/workflows/jekyll-gh-pages.yml
  _config.yml
  _layouts/default.html
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#848 [FIX] Fixed Issue #787
  index.html
  privacy.html
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#872 home button visible
  src/css/up.css
  up.html
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#869 Fixed website logo animation issue ! #844
  Feedback.html
  contact.html
  features.html
  team.html
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#889 [FIX] FAQ Section Glitches Fixed
  index.html
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#876 Add ambulance APIs
  Backend/Controllers/ambulanceController.js
  Backend/Models/Ambulance.js
  Backend/Models/User.js
  Backend/server.js
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#851 Sign up and sign in buttons are now in working.
  up.html
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#904 [FIX] Site Map Page Fixed
  sitemap.html
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#907 [FIX] FAQ Section Link Fixed
  index.html
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#914 [FIX] Menu Drop Down fixed for Bigger Screens
  responsive.css
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#954 [FIXED] [Bug]: Repetition in FAQ Section #953
  index.html
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#963 Update README.md and Contributing.md file
  Contributing.md
  README.md
  script.js
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#984 Update nearby.html
  nearby.html
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#1048 Footer is Not Responsive on Different Screen Sizes
  index.html
  style1.css
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#1055 Resolved: Favicon missing on subpage Pages and bugs in README file
  Feedback.html
  README.md
  index.html
  nearby.html
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#1054 Email validation checker while subscribing
  contact.html
  index.html
  team.html
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#1029 change the name of the ambuflow to hindi now its looks goods
  index.html
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#1041 [FIX] Fixes Issue #1039 and other bugs
  Feedback.html
  contact.html
  features.html
  nearby.html
  sitemap.html
  team.html
  up.html
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#806 Added Newsletter Valiadation | Toast Alerts | Smoth Scrolling | Issue #444
  index.html
Labels: gssoc-ext, level2

#972 Fixed hover issue on contact page of hover issue in quick links and contact info section.
  contact.html
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#1000 Some Changes in privacy.html file
  privacy.html
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#1079 Added UI functionality to 'Go to Team' and 'Go to Contact' buttons in nav.css file (by miss).
  src/css/navbar.css
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#1121 Followed same design of navbar in all webpages and resolved navbar conflicts
  Feedback.html
  features.html
  src/css/navbar.css
  team.html
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted
