Repository vimistify/AmbuFlow, pull requests merged in 2024-11, with the labels that each got.

#1169 Enhance Styling of Login and Get Started Buttons
  Backend/package-lock.json
  team.html
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#1173 Adding "remember me" to the signup and signin page connecting it to the local storage database for user authentication.
  Feedback.html
  jquery-1.12.js
  login.html
  login.js
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#1175 Enhancing the feedback section User interface and CSS styling and added the "thank you message"
  Feedback.html
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#1198 Added links to the footer section
  Backend/package-lock.json
  index.html
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#1199 Add/Enable PWA (Progressive Web App) done ! #1189 🌟🌟🌟
  icon-192x192.png
  icon-512x512.png
  index.html
  manifest.json
  scripts.js
  sw.js
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#1201 Add Edit Profile Feature in Profile Page done ! #1197 🟢🌟
  index.html
  profile.html
  profileedit.html
  testp.js
Labels: level3, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#1202 Contributors page created
  contributors/contributors.css
  contributors/contributors.html
  contributors/contributors.js
  index.html
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#1222 Improve total contributors page done ! #1221 🟢🟢
  contributors/contributors.css
  contributors/contributors.js
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1008 Now, social media authentication is in working.
  up.html
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#1083 modification in the footer of home page
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1176 Added Enhanced scroll back button with timeline on it for smoother functioning to ALL pages.
  contact.html
  features.html
  index.html
  nearby.html
  team.html
Labels: gssoc-ext, level2, hacktoberfest, hacktoberfest-accepted

#1210 adding dark mode styling to elements of home and contact page
  contact.html
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1212 Added all the contributors
  contributors/contributors.js
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1216 Fix 404 Page Redirection for Invalid Routes
  .htaccess
  404.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1218 Modified contact.html
  contact.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1224 Add Signup/Register page done ! #1223 🌟🌟
  index.html
  signup.css
  signup.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1226 Fixed the issue of social media links opening in the same tab
  Contactus.html
  Feedback.html
  SOS.html
  about.html
  contact.html
  homepage.html
  team.html
Labels: gssoc-ext, level2, hacktoberfest-accepted

#1228 contact section and contact us section icons colors and animation updated
  Contactus.html
  contact.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#803 New Cards Added in features
  features.html
Labels: level1, gssoc-ext, hacktoberfest, hacktoberfest-accepted

#1233 Made changes to login.html
  login.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1239 added enter button key board functinality of chatbot massege send section
  chatbot.html
Labels: gssoc-ext, level2, hacktoberfest-accepted
