Repository vimistify/AmbuFlow, pull requests merged in 2025-01, with the labels that each got.

#1243 Fixed Responsiveness
  index.html
Labels: level1, SWOC

#1253 redesigned About us page
  about.html
Labels: enhancement, level2, SWOC

#1259 Fixed Signup page in about page
  about.html
  up.html
Labels: level2, SWOC

#1260 Fixed Navbar buttons visibility in feedback page
  Feedback.html
Labels: SWOC, intermediate

#1266 Update features.html
  features.html
Labels: SWOC, intermediate
